### ISSUE TITLE
Support for new wp_open_body action hook for WP 5.2

### ISSUE THREAD

**Issue by roborourke** [humanmade/hm-gtm#13]
https://make.wordpress.org/core/2019/04/24/miscellaneous-developer-updates-in-5-2/

Right now the iframe fallback is output on a custom action that needs manually adding to a theme. This should be a fallback for WP versions less than 5.2 only.

**Comment by roborourke** [comment]
Note this update should be backwards compatible.

**Comment by waviaei** [comment]
@roborourke 
I was looking into why `<noscript>` was not being output and found `after_body` is [specified](https://github.com/humanmade/hm-gtm/blob/ab59419e53a26534d21089bc4af18e08448ee45c/inc/namespace.php#L20) instead of `wp_body_open`

Any plan to update this soon?

**Comment by roborourke** [comment]
It would be good to support this natively out of the box yes. It isn't planned in to any sprints right now but if you are open to contributing a PR it will happen faster. Thanks for the reminder Toru!

**Comment by roborourke** [comment]
Fixed in #37
