### ISSUE TITLE
GDPR compliance, consent, etc

### ISSUE THREAD

**Issue by jshwlkr** [humanmade/hm-gtm#15]
It'd be great, for me especially, if this plugin supported some kind of GDPR consent dialogue or integrated with something that did.

**Comment by roborourke** [comment]
Thanks for using the plugin @jshwlkr :) I don't think this is something I'd integrate directly or provide in this plugin as there are so many other 3rd party implementations out there, some of which you can even add and manage through GTM. This one just has a singular focus. Adding tag manager itself doesn't necessarily mean you'll be adding tracking or scripts that set cookies etc.

Take for example [Cookiebot](https://www.cookiebot.com/en/google-tag-manager-gdpr/?gclid=EAIaIQobChMIn6zT7b7N5AIVV-DtCh3cVQw3EAAYASAAEgIJm_D_BwE) or [this guide for iubenda](https://www.iubenda.com/en/help/1235-google-tag-manager-blocking-cookies) - they show you how to set up tag manager triggers for when a user consents to tracking.
