### ISSUE TITLE
fatal error on activation

### ISSUE THREAD

**Issue by jshwlkr** [humanmade/hm-gtm#16]
Which looks like this:  
  
`Fatal error: Uncaught Error: Call to undefined function HM\GTM\get_plugin_data() in /srv/www/wordpress-one/public_html/wp-content/plugins/hm-gtm/inc/namespace.php:194 Stack trace: #0 /srv/www/wordpress-one/public_html/wp-includes/class-wp-hook.php(286): HM\GTM\enqueue_scripts('') #1 /srv/www/wordpress-one/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /srv/www/wordpress-one/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #3 /srv/www/wordpress-one/public_html/wp-includes/script-loader.php(2537): do_action('wp_enqueue_scri...') #4 /srv/www/wordpress-one/public_html/wp-includes/class-wp-hook.php(286): wp_enqueue_scripts('') #5 /srv/www/wordpress-one/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #6 /srv/www/wordpress-one/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #7 /srv/www/wordpress-one/public_html/wp-includes/general-template.php(2745): do_action('wp_head') #8 /srv/www/wordpress-one/public_html/wp-conten in /srv/www/wordpress-one/public_html/wp-content/plugins/hm-gtm/inc/namespace.php on line 194`  
  
On WP 5.2.2 and PHP 7.2.19 .

**Comment by roborourke** [comment]
That's pretty strange, `get_plugin_data()` is a global function and it's not having any issues with the other global functions. I normally load this as a mu-plugin so I'll see what's up.

**Comment by roborourke** [comment]
I can't reproduce this at all. Does it happen every time?

**Comment by jshwlkr** [comment]
It was at the time. (I haven't tried it since.)

**Comment by roborourke** [comment]
I'm not sure how to help further at the moment then. Can you confirm my assumption that you're adding this as a regular plugin in `wp-content/plugins` and hitting activate via the admin?

**Comment by jshwlkr** [comment]
I believe that was my workflow at the time.

**Comment by roborourke** [comment]
@jshwlkr it was my fault - `get_plugin_data()` is only available in the admin _or_ when logged in which is what caught me out. Fixed now.
