### ISSUE TITLE
Escaping

### ISSUE THREAD

**Issue by paulgibbs** [humanmade/hm-gtm#2]
Do each of the data layer variables need to have a generic escaping or sanitisation function applied to them? Like, I don't know, `esc_js` ?

**Comment by sanchothefat** [comment]
I wouldn't have thought so when they're passed to `json_encode()` unless I'm missing something. It could probably be improved by switching to `wp_json_encode()` though of course.

**Comment by rmccue** [comment]
`json_encode` will handle ensuring the values are passed into JS correctly, but you may need to do escaping (HTML/otherwise) wherever you're using those values.

**Comment by roborourke** [comment]
That's down to how the data layer is used within GTM so I think it's outside the scope for this plugin.
