### ISSUE TITLE
Switch comment count to cached function

### ISSUE THREAD

**Issue by rmccue** [humanmade/hm-gtm#32]
`dataLayer.post.comments` uses `get_comment_count()`, which [makes direct queries to the database](https://github.com/WordPress/wordpress-develop/blob/f90515acdb5313e14445868e25b2b19acaa58ee7/src/wp-includes/comment.php#L383-L420). This is pretty useless, since the data doesn't change often, and we're only using a single integer (which is almost always zero!) anyway.

Using [`wp_count_comments()`](https://github.com/WordPress/wordpress-develop/blob/f90515acdb5313e14445868e25b2b19acaa58ee7/src/wp-includes/comment.php#L1401-L1430) instead uses the cache (and yeah, don't get me started on the naming of these...). This avoids unnecessary queries and improves performance basically for free - the function returns basically the same thing.

**Comment by roborourke** [comment]
Fixed in #37
