### ISSUE TITLE
`after_body` is not a core WordPress hook

### ISSUE THREAD

**Issue by johnbillion** [humanmade/hm-gtm#33]
In https://github.com/humanmade/hm-gtm/blob/0f7c9b6f5b06f1cb83c404b8141cfcab4eceac64/inc/namespace.php#L19 the `after_body` hook is used to call the `output_tag()` function. This is not a core WordPress hook.

I think this should be replaced with `wp_body_open`, but that needs confirming for sure.

**Comment by roborourke** [comment]
Fixed in #37
