### ISSUE TITLE
Defer strategy

### ISSUE THREAD

**Issue by svandragt** [humanmade/hm-gtm#34]
Morning, I see that this script is included in the footer, and would be a good candidate to assign a `defer` strategy introduced to WordPress 6.3 / 6.4? If so it can be placed in the header as it would be no longer blocking.

Let me know what you think and I will contribute the patch.

**Comment by roborourke** [comment]
This is the event tracking script you're referring to? Yeah adding `defer` makes total sense, please feel free to contribute.

**Comment by roborourke** [comment]
Fixed in #37
